### ISSUE TITLE
Logging says "Finished" but the collection isn't added

### ISSUE THREAD

**Issue by 8zu** [fenglisch/bgg-bulk-upload#1]
Hi, thank you for the program!

I used https://github.com/fenglisch/bgg-names-to-ids to generate the CSV, then I ran

```
node bgg-bulk-upload.js ~/Downloads/bgg-game-to-id.csv -u $username -p $password
```

The logging shows
```
 [Success] Access to your existing BGG collection was successful. Found 0 items.
 The ChromeDriver could not be found on the current PATH, trying Selenium Manager
 [Status update] Logging in.
 [Success] Login succeeded.
 [Finished]
```

But then I checked the BGG website and my collection is still empty.

**Comment by fenglisch** [comment]
Hey, thanks for the comprehensive bug report!

You can add two additional parameters to the end of the command, `debugging-mode` and `show-browser`. In debugging mode, the program prints the ID's it found in your input file to the console. I suspect this to be the error source (although it would be weird if you created the file with my other program). 

This will not solve your problem, but at least we get more information.

**Comment by 8zu** [comment]
hi! OK, I add the params, it opened the browser and logged in. But then after logging in it just printed "Finished" and exited.

```
 [Success] Access to your existing BGG collection was successful. Found 0 items.
 [Debugging mode] ID's from your FILE:

 The ChromeDriver could not be found on the current PATH, trying Selenium Manager
 [Status update] Logging in.
 [Success] Login succeeded.


 [Finished]
```

<img width="1103" alt="Screenshot 2023-04-03 at 15 26 05" src="https://user-images.githubusercontent.com/27755954/229640799-6dfd0824-b14b-44bc-8097-d239e01e86ea.png">

I wonder if the `ChromeDriver` is necessary for this to work. Perhaps I can try to find it.

**Comment by 8zu** [comment]
Update:
I downloaded the ChromeDriver https://chromedriver.storage.googleapis.com/index.html?path=111.0.5563.64/  and added it to my path. It is able to achieve the same result but not more. (Logged in but stopped at the main page)

Logging:
```
 [Success] Access to your existing BGG collection was successful. Found 0 items.
 [Debugging mode] ID's from your FILE:

 [Status update] Logging in.
 [Success] Login succeeded.
 [Finished]
```

**Comment by 8zu** [comment]
Probably worth mentioning my system

Apple M1 Max
macOS Ventura 13.2.1
Chrome Version 111.0.5563.146 (Official Build) (arm64)

**Comment by fenglisch** [comment]
The warning `The ChromeDriver could not be found` is not an issue, as long as it finds the Chrome Driver with the Selenium Manager (which it apparently did already in the first hand, otherwise logging in would not have worked).

The problem is indeed that it cannot read the IDs from the file. After `[Debugging mode] ID's from your FILE:`, there should be a list of IDs. 

Can you copy the content of the file into this issue thread?

And you can also check the path, although it looks good, by running the command `$ cat ~/Downloads/bgg-game-to-id.csv`, which prints the content of the file to the console

**Comment by fenglisch** [comment]
And is it at least correct that the collection you're adding games to is completely empty, as ` [Success] Access to your existing BGG collection was successful. Found 0 items.` indicates?

**Comment by 8zu** [comment]
Yes, the collection is currently empty. As I am migrating my account.

> The problem is indeed that it cannot read the IDs from the file

Interesting. The CSV file is created by your other program. But I will read up to see what's wrong with the format!

**Comment by fenglisch** [comment]
If you want you can copy & paste the content of the file so I can check if it works on my laptop.

**Comment by 8zu** [comment]
sure it's like

(removed)

**Comment by fenglisch** [comment]
Thank you! I found the mistake and fixed it with my latest commit. You can download the latest version of `bgg-bulk-upload.js` and then it should work :-)

**Comment by 8zu** [comment]
Yes, this worked! Thank you!
